### ISSUE TITLE
Need a bit help

### ISSUE THREAD

**Issue by docfaizal** [SushiWaUmai/dotfiles#1]
Bro can u list the patches u have used in your dwm build plz :), i am trying ur setup but i want to build my dwm build with flexipatch
![rice](https://user-images.githubusercontent.com/107258640/233201961-164ab4dc-4c0a-48ac-bbb6-2a57516569c4.png)

**Comment by ugnmura** [comment]
Uh ohh, I really sorry but I don't really remember all the patches I used, furthermore I edited a lot of the dwm code myself (such as the border around the bar) so I think using flexipatch is kinda hard to do.

**Comment by docfaizal** [comment]
> Uh ohh, I really sorry but I don't really remember all the patches I used, furthermore I edited a lot of the dwm code myself (such as the border around the bar) so I think using flexipatch is kinda hard to do.

Np bro, just tell me why first window opens in monocole layout, is there any way to toggle that off in config.def.h?

**Comment by ugnmura** [comment]
Seems like some patch changed the way it handles the first window, I'm just gonna fix it now.

https://github.com/SushiWaUmai/dotfiles/blob/164c401540a47e67fd78778f923f510470ca1c70/suckless/dwm/dwm.c#L1710
